# Site settings
title: 'Jennie Snider'
email: 'jennie@jenniesnider.com'
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jenniesnider.com" # the base hostname & protocol for your site

linkedin_username: 'jenniesnider'
github_username: 'orangedalek'

# Build settings
markdown: kramdown
